version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mvc_php
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    working_dir: /var/www/html
