version: "3.8"

services:
  php:
    image: php:8.2-apache
    container_name: mvc_php
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    working_dir: /var/www/html

  composer:
    image: composer:2
    container_name: mvc_composer
    volumes:
      - .:/app
    working_dir: /app
